# Generated by Django 5.2.2 on 2025-06-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_user_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_online',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
